name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk git zip unzip python3-pip
          pip3 install buildozer
      
      - name: Build APK
        run: |
          # نحدد SDK و NDK يدوياً
          export ANDROIDSDK=/usr/local/lib/android/sdk
          export ANDROIDNDK=/usr/local/lib/android/sdk/ndk/27.3.13750724
          export ANDROIDAPI=33
          export ANDROIDMINAPI=21
          buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlNisr-APK
          path: bin/*.apk
